//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceScr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceScr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeManagement.Resources.ResourceScr", typeof(ResourceScr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string addProject {
            get {
                return ResourceManager.GetString("addProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subtask.
        /// </summary>
        public static string addSubtask {
            get {
                return ResourceManager.GetString("addSubtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string addTag {
            get {
                return ResourceManager.GetString("addTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you forgot the details of your task? Write a remark for it!.
        /// </summary>
        public static string advRemark {
            get {
                return ResourceManager.GetString("advRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders will always help you to be in the right place at the right time.
        /// </summary>
        public static string advReminders {
            get {
                return ResourceManager.GetString("advReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All events.
        /// </summary>
        public static string AllEvents {
            get {
                return ResourceManager.GetString("AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All task.
        /// </summary>
        public static string AllTask {
            get {
                return ResourceManager.GetString("AllTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at .
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes before.
        /// </summary>
        public static string b10m {
            get {
                return ResourceManager.GetString("b10m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes before.
        /// </summary>
        public static string b15m {
            get {
                return ResourceManager.GetString("b15m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day before.
        /// </summary>
        public static string b1d {
            get {
                return ResourceManager.GetString("b1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour before.
        /// </summary>
        public static string b1h {
            get {
                return ResourceManager.GetString("b1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 day before.
        /// </summary>
        public static string b2d {
            get {
                return ResourceManager.GetString("b2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours before.
        /// </summary>
        public static string b2h {
            get {
                return ResourceManager.GetString("b2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes before.
        /// </summary>
        public static string b30m {
            get {
                return ResourceManager.GetString("b30m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes before.
        /// </summary>
        public static string b5m {
            get {
                return ResourceManager.GetString("b5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to timetable.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet.
        /// </summary>
        public static string cabinet {
            get {
                return ResourceManager.GetString("cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this task can&apos;t be added to your todo list. You haven&apos;t enough free time. Try to change your Day Limit or divide your task..
        /// </summary>
        public static string cantAddToList {
            get {
                return ResourceManager.GetString("cantAddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed on.
        /// </summary>
        public static string CompletedOn {
            get {
                return ResourceManager.GetString("CompletedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks compleated during last week.
        /// </summary>
        public static string CompletedOnWeek {
            get {
                return ResourceManager.GetString("CompletedOnWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of completion.
        /// </summary>
        public static string CompleteLevel {
            get {
                return ResourceManager.GetString("CompleteLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation of the time range of the assignment with complexity level.
        /// </summary>
        public static string ComplexitySettings {
            get {
                return ResourceManager.GetString("ComplexitySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string contains {
            get {
                return ResourceManager.GetString("contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create limits for a day.
        /// </summary>
        public static string createDayLimit {
            get {
                return ResourceManager.GetString("createDayLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string createProject {
            get {
                return ResourceManager.GetString("createProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new task.
        /// </summary>
        public static string createTask {
            get {
                return ResourceManager.GetString("createTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date for planning.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string DefaultProject {
            get {
                return ResourceManager.GetString("DefaultProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DeleteQustion {
            get {
                return ResourceManager.GetString("DeleteQustion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do task today.
        /// </summary>
        public static string doToday {
            get {
                return ResourceManager.GetString("doToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every two week.
        /// </summary>
        public static string E2w {
            get {
                return ResourceManager.GetString("E2w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        public static string Ed {
            get {
                return ResourceManager.GetString("Ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save for all.
        /// </summary>
        public static string EditAll {
            get {
                return ResourceManager.GetString("EditAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        public static string Em {
            get {
                return ResourceManager.GetString("Em", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert needs informations about  Star or End Date.
        /// </summary>
        public static string ErrorAlert {
            get {
                return ResourceManager.GetString("ErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range is to small for this complexity.
        /// </summary>
        public static string ErrorComplexity {
            get {
                return ResourceManager.GetString("ErrorComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date should be before End date.
        /// </summary>
        public static string ErrorDateOrder {
            get {
                return ResourceManager.GetString("ErrorDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of repeating stop should be after End date.
        /// </summary>
        public static string ErrorDateStopOrder {
            get {
                return ResourceManager.GetString("ErrorDateStopOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This day has already been planed.
        /// </summary>
        public static string ErrorNoTime {
            get {
                return ResourceManager.GetString("ErrorNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can only contain letters, numbers, underscores and punctuation.
        /// </summary>
        public static string ErrorRegulExpr {
            get {
                return ResourceManager.GetString("ErrorRegulExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be filled.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is too long.
        /// </summary>
        public static string ErrorStrLen {
            get {
                return ResourceManager.GetString("ErrorStrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time estimation.
        /// </summary>
        public static string estimation {
            get {
                return ResourceManager.GetString("estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        public static string Ew {
            get {
                return ResourceManager.GetString("Ew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        public static string execution {
            get {
                return ResourceManager.GetString("execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every year.
        /// </summary>
        public static string Ey {
            get {
                return ResourceManager.GetString("Ey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish at.
        /// </summary>
        public static string FinishAt {
            get {
                return ResourceManager.GetString("FinishAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Time.
        /// </summary>
        public static string freeTime {
            get {
                return ResourceManager.GetString("freeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        public static string Future {
            get {
                return ResourceManager.GetString("Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate task list.
        /// </summary>
        public static string GenerateList {
            get {
                return ResourceManager.GetString("GenerateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string greeting {
            get {
                return ResourceManager.GetString("greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have a local account.
        /// </summary>
        public static string IfNoAccount {
            get {
                return ResourceManager.GetString("IfNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is urgent.
        /// </summary>
        public static string IsUrgent {
            get {
                return ResourceManager.GetString("IsUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s too late =(.
        /// </summary>
        public static string itsPast {
            get {
                return ResourceManager.GetString("itsPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need more settings?.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need.
        /// </summary>
        public static string need {
            get {
                return ResourceManager.GetString("need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New alert.
        /// </summary>
        public static string newAlert {
            get {
                return ResourceManager.GetString("newAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New event.
        /// </summary>
        public static string newEvent {
            get {
                return ResourceManager.GetString("newEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string newProject {
            get {
                return ResourceManager.GetString("newProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag.
        /// </summary>
        public static string newTag {
            get {
                return ResourceManager.GetString("newTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no alerts.
        /// </summary>
        public static string NoAlerts {
            get {
                return ResourceManager.GetString("NoAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are no available tasks. You can read interesting book or just relax. .
        /// </summary>
        public static string noAvailableTasks {
            get {
                return ResourceManager.GetString("noAvailableTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Due Date.
        /// </summary>
        public static string NoDueDate {
            get {
                return ResourceManager.GetString("NoDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no plans for this day.
        /// </summary>
        public static string NothingPlaning {
            get {
                return ResourceManager.GetString("NothingPlaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do.
        /// </summary>
        public static string nothingToDo {
            get {
                return ResourceManager.GetString("nothingToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ToDo list is empty.
        /// </summary>
        public static string noTodo {
            get {
                return ResourceManager.GetString("noTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No urgent, important.
        /// </summary>
        public static string NoUrgentImportant {
            get {
                return ResourceManager.GetString("NoUrgentImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No urgent, no important.
        /// </summary>
        public static string NoUrgentNoImportant {
            get {
                return ResourceManager.GetString("NoUrgentNoImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On background.
        /// </summary>
        public static string OnBackground {
            get {
                return ResourceManager.GetString("OnBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable on.
        /// </summary>
        public static string onDate {
            get {
                return ResourceManager.GetString("onDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of time you need for background events.
        /// </summary>
        public static string ParallelismPercentage {
            get {
                return ResourceManager.GetString("ParallelismPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent project.
        /// </summary>
        public static string ParentProject {
            get {
                return ResourceManager.GetString("ParentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project.
        /// </summary>
        public static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readiness.
        /// </summary>
        public static string Readiness {
            get {
                return ResourceManager.GetString("Readiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterForm {
            get {
                return ResourceManager.GetString("RegisterForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneously.
        /// </summary>
        public static string Simultaneously {
            get {
                return ResourceManager.GetString("Simultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take control of your time!.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        public static string StartAt {
            get {
                return ResourceManager.GetString("StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subprojects.
        /// </summary>
        public static string subprojects {
            get {
                return ResourceManager.GetString("subprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.
        /// </summary>
        public static string tag {
            get {
                return ResourceManager.GetString("tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag1 {
            get {
                return ResourceManager.GetString("Tag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity.
        /// </summary>
        public static string TaskComplexity {
            get {
                return ResourceManager.GetString("TaskComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string TaskDeadline {
            get {
                return ResourceManager.GetString("TaskDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string TaskDueDate {
            get {
                return ResourceManager.GetString("TaskDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string TaskEstimation {
            get {
                return ResourceManager.GetString("TaskEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent task.
        /// </summary>
        public static string TaskParentTask {
            get {
                return ResourceManager.GetString("TaskParentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TaskPriority {
            get {
                return ResourceManager.GetString("TaskPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string TaskProject {
            get {
                return ResourceManager.GetString("TaskProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string tasks {
            get {
                return ResourceManager.GetString("tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string TaskStartDate {
            get {
                return ResourceManager.GetString("TaskStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till.
        /// </summary>
        public static string till {
            get {
                return ResourceManager.GetString("till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тime limitation.
        /// </summary>
        public static string TimeL {
            get {
                return ResourceManager.GetString("TimeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much free time should be filled.
        /// </summary>
        public static string TimeToFill {
            get {
                return ResourceManager.GetString("TimeToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time zone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to backlog.
        /// </summary>
        public static string toBacklog {
            get {
                return ResourceManager.GetString("toBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To default.
        /// </summary>
        public static string ToDefault {
            get {
                return ResourceManager.GetString("ToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent, no important.
        /// </summary>
        public static string UrgentNoImportant {
            get {
                return ResourceManager.GetString("UrgentNoImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string VeryHigh {
            get {
                return ResourceManager.GetString("VeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week before.
        /// </summary>
        public static string wb {
            get {
                return ResourceManager.GetString("wb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for tasks and events.
        /// </summary>
        public static string WorkingTime {
            get {
                return ResourceManager.GetString("WorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as.
        /// </summary>
        public static string YouLogged {
            get {
                return ResourceManager.GetString("YouLogged", resourceCulture);
            }
        }
    }
}
